[package]
name = "cras_cbindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen = "0.24"
clap = { version = "3.2.23", features = ["derive"] }
