[package]
name = "cras"
version = "0.1.1"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.68"
getrandom = "0.2.7"
glob = "0.3.0"
libc = "0.2.44"
log = "0.4.17"
nix = "0.26.2"
once_cell = "1.17.0"
openssl = "0.10.48"
protobuf = "3.2.0"
regex = "1.6.0"
serde_json = "1.0.64"
syslog = "6.0.1"

cras_dlc = { version = "*" }
audio_processor = { version = "*" }
cras_features_backend = { version = "*" }

[build-dependencies]
protobuf-codegen = "3.2.0"
protobuf-parse = "3.2.0"
