[package]
name = "cras_rust"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.44"
cras_dlc = { version = "*", optional = true }

[workspace]
members = [
    "binding_generator",
    "cras_dlc",
]

[profile.release]
lto = true
panic = "abort"
overflow-checks = true

[patch.crates-io]
cras_dlc = { path = "cras_dlc" }

# If your `protoc --version` is less than 3.13, you need to add
# `--experimental_allow_proto3_optional` to protoc so system_api builds.
# A helper is provided in hacks/bin.
system_api = { git = "https://chromium.googlesource.com/chromiumos/platform2", version = ">=0.24.53" } # ignored by ebuild
# Replace the above with the below when making testing in-repo changes in chroot.
# system_api = { path = "../../../../../../platform2/system_api" } # ignored by ebuild
