[package]
name = "cras"
version = "0.1.1"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.68"
libc = "0.2.44"
log = "0.4.17"
protobuf = "3.2.0"

cras_common = { version = "*" }
cras_dlc = { version = "*" }
audio_processor = { version = "*" }
cras_features_backend = { version = "*" }

[build-dependencies]
protobuf-codegen = "3.2.0"
protobuf-parse = "3.2.0"
