[package]
name = "cras_rust"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.68"
libc = "0.2.44"
log = "0.4.17"
syslog = "6.0.1"

cras_dlc = { version = "*", optional = true }
audio_processor = { version = "*", path = "../../audio_processor" }

[workspace]
members = [
    "binding_generator",
    "cras_dlc",
]

[profile.release]
lto = true
panic = "abort"
overflow-checks = true

[patch.crates-io]
cras_dlc = { path = "cras_dlc" }

system_api = { git = "https://chromium.googlesource.com/chromiumos/platform2", version = ">=0.24.53" } # ignored by ebuild
# Replace the above with the below when making testing in-repo changes in chroot.
# system_api = { path = "../../../../../../platform2/system_api" } # ignored by ebuild
