[package]
name = "libcras"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[lib]
path = "src/libcras.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.36"
audio_streams = "*"
cras-sys = { version = "*", path = "../cras-sys" }
data_model = "*"
futures = "*"
libc = "*"
libchromeos = { path = "../../../../../platform2/libchromeos-rs/" } # provided by ebuild
log = "0.4"
nix = { version = "0.26", features = ["socket"] }
serde = "1.0.125"
tokio = { version = "1.19.2", features = ["rt", "net", "time"]}
