[package]
name = "libcras"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2018"

[lib]
path = "src/libcras.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.36"
audio_streams = "*"
cros_async = "*"
cras-sys = { path = "../cras-sys" } # provided by ebuild
data_model = "*"
libc = "*"
libchromeos = { path = "../../../../../platform2/libchromeos-rs/" } # provided by ebuild
serde = "1.0.125"

[dependencies.futures]
version = "*"

[patch.crates-io] # ignored by ebuild
audio_streams = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/audio_streams-0.1.0/" } # ignored by ebuild
base_event_token_derive = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/base_event_token_derive-0.1.0/" } # ignored by ebuild
crosvm-base = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/crosvm-base-0.1.0/" } # ignored by ebuild
cros_async = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/cros_async-0.1.0/" } # ignored by ebuild
data_model = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/data_model-0.1.0/" } # ignored by ebuild
io_uring = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/io_uring-0.1.0/" } # ignored by ebuild
sys_util = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/sys_util-0.1.0/" } # ignored by ebuild
sys_util_core = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/sys_util_core-0.1.0/" } # ignored by ebuild
sync = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/sync-0.1.149/" } # ignored by ebuild
