[package]
name = "rock"
version = "0.1.0"
edition = "2021"
authors = ["The ChromiumOS Authors"]

[dependencies]
audio_processor = "*"
anyhow = "1.0.75"
clap = { version = "4.5.4", features = ["derive"] }
hound = "3.5.0"
rustfft = "6.1.0"
