[package]
name = "sof_tests"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.5.4", features = ["derive"]}
serde = { version = "1.0.52", features = ["derive"]}
serde_json = "1.0.96"
