[package]
name = "cras-sys"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"
exclude = ["*"]
include = ["Cargo.toml", "build.rs", "src/lib.rs", "src/gen.rs"]

[dependencies]
audio_streams = { path = "../../../audio_streams" } # provided by ebuild
data_model = { path = "../../../../../platform/crosvm/data_model" } # provided by ebuild

[build-dependencies]
bindgen = "0.56"
