[package]
name = "audio_diagnostics"
version = "0.1.1"
authors = ["The ChromiumOS Authors"]
edition = "2018"

[dependencies]
anyhow = "1.0.68"
log = "0.4.17"
glob = "0.3.0"
regex = "1.6.0"
serde = { version = "1.0.52", features = ["derive"]}
serde_json = "1.0.96"

cras_common = "*"
libcras = "*"
