[package]
name = "cras_tests"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
audio_streams = { path = "../../../../../platform/crosvm/common/audio_streams" } # provided by ebuild
dbus = "0.9"
getopts = "0.2.18"
hound = "3.4.0"
libcras = { path = "../libcras" } # provided by ebuild
sys_util = { path = "../../../../../platform/crosvm/common/sys_util" } # provided by ebuild
thiserror = "1.0.20"

[build-dependencies]
chromeos-dbus-bindings = { path = "../../../../../platform2/chromeos-dbus-bindings" } # provided by ebuild

[profile.release]
lto = true
panic = 'abort'
overflow-checks = true
