[package]
name = "cras_tests"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2018"

[dependencies]
audio_streams = "*" # provided by ebuild
clap = { version = "3.1.10", features = ["derive"] }
dbus = "0.9"
hound = "3.4.0"
libchromeos = { path = "../../../../../platform2/libchromeos-rs/" } # provided by ebuild
libcras = { path = "../libcras" } # provided by ebuild
serde_json = "1.0.64"
thiserror = "1.0.20"

[build-dependencies]
chromeos-dbus-bindings = { path = "../../../../../platform2/chromeos-dbus-bindings" } # provided by ebuild

[profile.release]
lto = true
panic = 'abort'
overflow-checks = true

[patch.crates-io] # ignored by ebuild
audio_streams = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/audio_streams-0.1.0/" } # ignored by ebuild
base_event_token_derive = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/base_event_token_derive-0.1.0/" } # ignored by ebuild
crosvm-base = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/crosvm-base-0.1.0/" } # ignored by ebuild
cros_async = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/cros_async-0.1.51/" } # ignored by ebuild
data_model = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/data_model-0.1.50/" } # ignored by ebuild
io_uring = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/io_uring-0.1.51/" } # ignored by ebuild
serde_keyvalue = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/serde_keyvalue-0.1.50/" } # ignored by ebuild
serde_keyvalue_derive = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/serde_keyvalue_derive-0.1.50/" } # ignored by ebuild
sync = { path = "../../../../../../chroot/usr/lib/cros_rust_registry/registry/sync-0.1.149/" } # ignored by ebuild
minijail = { path = "../../../../../platform/minijail/rust/minijail" } # ignored by ebuild
