[package]
name = "cras_tests"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
audio_streams = "*"
cras-sys = "*"
clap = { version = "4.5.4", features = ["derive"] }
dasp_sample = "0.11"
dbus = "0.9"
either = "1.9.0"
hound = "3.4.0"
libchromeos = "*"
libcras = "*"
nix = { version = "0.28", features = ["signal"] }
serde_json = "1.0.96"
thiserror = "1.0.20"
libc = "0.2"

[build-dependencies]
chromeos-dbus-bindings = "*"
