[package]
name = "cras_tests"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"

[dependencies]
audio_streams = "*"
clap = { version = "3.1.10", features = ["derive"] }
dbus = "0.9"
hound = "3.4.0"
libchromeos = "*"
libcras = "*"
nix = { version = "0.26", features = ["signal"] }
serde_json = "1.0.96"
thiserror = "1.0.20"
libc = "0.2"

[build-dependencies]
chromeos-dbus-bindings = "*"
